services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./internal/llm/prompts/prompts.toml:/app/prompts.toml
      - .env:/app/.env
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - monitoring

  newrelic-infra:
    image: newrelic/infrastructure:latest
    container_name: newrelic-infra
    env_file:
      - .nrenv
    privileged: true
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  pgdata:
    driver: local